name: 'Update Local Files'
description: 'Updated the locale data for the build'
inputs:
  workpath:
    description: 'The folder to copy the files to'
    required: true
    default: '~'
runs:
  using: "composite"
  steps: 
     - run: if (Test-Path -Path D:\arma3work\drive\${{ inputs.workpath }}) { Write-Output "Path exists!"; rm -r D:\arma3work\drive\${{ inputs.workpath }}\* } else { Write-Output "Path doesn't exist."; mkdir D:\arma3work\drive\${{ inputs.workpath }} }
       shell: powershell
       
     - run: Copy-item -Force -Recurse -Verbose * -Destination "D:\arma3work\drive\${{ inputs.workpath }}\" -Exclude (".github",".gitattributes","source", "*.png", ".git", ".gitignore")
       shell: powershell
